service: typed-serverless

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  serverless-offline:
    httpPort: 4000
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    stages:
    - dev
  
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1

functions:
  ping:
    handler: src/functions.ping
    description: Lambda function with typescript
    memorySize: 256
    events:
      - http:
          path: /ping
          method: get
          cors: true
