service: typed-serverless

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  # - serverless-webpack

# package:
#   individually: true

custom:
  serverless-offline:
    httpPort: 4000
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: false
    packager: 'npm'
  dynamodb:
    start:
      port: 5000
      inMemory: true
      migrate: true
    stages:
      - dev
    migration:
      dir: offline/migrations
  
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1

functions:
  getData:
    handler: src/dataGet.getData
    description: Lambda function to get data
    memorySize: 256
    events:
      - http:
          path: /get
          method: get
          cors: true
          
  postData:
    handler: src/dataPost.postData
    description: Lambda function to post data
    memorySize: 256
    events:
      - http:
          path: /post
          method: post
          cors: true

  deleteData:
    handler: src/dataDelete.deleteData
    description: Lambda function to delete data
    memorySize: 256
    events:
      - http:
          path: /delete
          method: delete
          cors: true